(function(){var i=void 0,k=true,n=null,o=false,p=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b};function q(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function ba(){}function ca(a){var b=[];r(new ba,a,b);return b.join("")}
function r(a,b,c){switch(typeof b){case "string":s(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==n){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),r(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),s(e,c),c.push(":"),r(a,f,c),d=","));c.push("}");
break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var u={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},da=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function s(a,b){b.push('"',a.replace(da,function(a){if(a in u)return u[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return u[a]=e+b.toString(16)}),'"')};function v(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}function w(a){return typeof a!=="undefined"}function y(a){return typeof a==="string"}function z(){return(new Date).getTime()}function B(a,b){if((!!a&&a.constructor===Object)===k)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===o)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===o)break}}
function C(a,b){var c;a:{c=0;for(var d=a.length;c<d;c++)if(b(a[c]))break a;c=-1}if(c>-1)return a[c]}var D=p.setInterval,F=p.clearInterval,G=p.setTimeout;function ea(a){G(a,0)}function fa(){var a=w(p.XDomainRequest);return w(p.XMLHttpRequest)&&"withCredentials"in new p.XMLHttpRequest?new p.XMLHttpRequest:a?new p.XDomainRequest:n}
function ga(a,b,c){var d=fa();d===n?c(n):(H(function(){d.open("GET",a,k)}),d.onload=function(){d.responseText?b(d):c(d)},d.onerror=function(){c(d,"onerror")},d.timeout=1E3,d.ontimeout=function(){c(d,"timeout")},ea(function(){H(function(){d.send(n)})}))}function H(a){try{a()}catch(b){}};var I={};I.F=function(){try{I.create("_cb_test","1",1);var a=I.b("_cb_test");I.remove("_cb_test");return a==="1"}catch(b){return o}};I.b=function(a){a+="=";var b="";B(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),o});return b};
I.create=function(a,b,c){var d=p._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(z()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};I.remove=function(a){return I.b(a)?I.create(a,"",-86400):""};var J={};J.a=function(a){var b=p._sf_async_config;if(!a&&b&&b.noCookies)return n;if(J.a.o!==i)return J.a.o;var a=z()+"",c,d;try{if((d=p.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return J.a.o=d}catch(e){}return J.a.o=n};J.b=function(a){var b=J.a();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&z()>c)?(J.remove(a),""):b.getItem(a)||""};
J.create=function(a,b,c){var d=J.a();if(d){var e=new Date;e.setTime(z()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};J.remove=function(a){var b=J.a();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function K(a){this.r=a||"";this.O=J.a()!==n||I.F();this.M=o;ha(this)}function ha(a){if(!I.b("_cb_ls")){var b=J.a()!==n,c=I.b("_SUPERFLY_lockout");c&&B(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,k)});var d=I.b("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,k),I.remove("_chartbeat3"));b&&((b=I.b("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,k),(b=I.b("_chartbeat5"))&&a.create("_chartbeat5",b,60,k));I.create("_cb_ls","1",34128E3)}}
K.prototype.create=function(a,b,c,d){a=d?a:this.r+a;(J.a()?J:I).create(a,b,c);J.a()&&I.create(a,b,c)};K.prototype.b=function(a,b){var a=b?a:this.r+a,c=(J.a()?J:I).b(a);if(!c&&J.a()&&(c=I.b(a))&&I.b("_cb_ls")){this.M=k;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}J.create(a,c,d)}return c};K.prototype.remove=function(a,b){a=b?a:this.r+a;(J.a()?J:I).remove(a);J.a()&&I.remove(a)};function L(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return n;var d=a.ownerDocument.documentElement,e=0,f=w(c)?c+1:-1;y(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return n}function ia(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")};var ja="z";function M(){w(p._cb_shared)||(p._cb_shared={});return p._cb_shared};function N(a,b){var c=M(),c=(w(i)&&!w(c.m)?i:c.m)||[];c.push.apply(c,arguments);M().m=c};function ka(){var a=n;B(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical"){var c=b.href,d="",e="",f="",g="";if(c){g=document.createElement("a");b=p.location;if(!/^https?:/.test(c)&&c.indexOf("javascript:")!==0&&c.indexOf("app:")<0)if(c.indexOf("//")===0)c=b.protocol+c;else if(c.indexOf("/")===0)d=b.protocol,d=(e=b.port)?d==="http:"&&e==="80"||d==="https:"&&e==="443":k,d=d?"":b.port,c=b.protocol+"//"+b.hostname+(d?":"+d:"")+c;else{d=document.baseURI||b.href;e=d.indexOf("?");e===
-1&&(e=d.indexOf("#"));if(e===-1)e=d.length;e=d.lastIndexOf("/",e);c=e===-1?"/"+c:d.substr(0,e)+"/"+c}g.href=c;d=g.pathname;e=g.search;f=g.protocol;g=g.hash;d.charAt(0)!=="/"&&(d="/"+d);if(f==="")f=b.protocol;f==="javascript:"&&(g=d="")}a=O(d)+e+g;return o}});return a}for(var la={},P=0;P<81;P++)la["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(P)]=k;
function ma(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return la[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function O(a){if(!y(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,ma);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function na(a){var b,c;b=a.domain;c=p.location.hostname.replace(/^www\./,"");return(p.location.protocol==="https:"?"https:":"http:")+"//mab.chartbeat.com/mab_strategy/headline_testing/get_strategy/?host="+encodeURIComponent(b)+"&domain="+encodeURIComponent(c)+"&path="+encodeURIComponent(a.path)}
function oa(a,b,c){var d,e,f;ga(a,function(a){var g;g=(a=q(a.responseText))&&a.constructor===Object&&y(a.status)&&(a.data&&a.data.constructor===Object||a.data===n)?{H:a.status,h:a.data,P:a.code,Q:a.message}:n,a=g;if(a===n)c();else if(a.H==="success"){d={};f=e=0;if(a.h)a.h.experiments&&(d=a.h.experiments),w(a.h.probability_is_lift)&&(e=a.h.probability_is_lift),w(a.h.probability_is_control)&&(f=a.h.probability_is_control);b(d,[e,f])}else c()},c)}
function pa(a,b,c){var d=[],e=b.e;if(e==="l"||e==="c")b=new qa("lift_exp","","",b,e,"",""),b.j=k,d.push(b);return d=d.concat(ra(a,c,e))}function sa(a,b){var c=[new Q("l",a[0],""),new Q("c",a[1],""),new Q("m",1-a[0]-a[1],"")];return ta(c,b.lift_exp)||c[2]}function ra(a,b,c){var d=[];B(a,function(a,f){var g=ua(f,a,c,b[f]);w(g)&&d.push(g)});return d}
function ua(a,b,c,d){var e=b.location,f=b.specific_location,g,j,h=b.metadata;if(y(h)&&h.length>0&&((h=q(h))&&h.version==2&&(g=h.sub_location),h&&h.version==3))g=h.sub_location,j=h.initial_content;g=w(g)?g:"";j=w(j)?j:"";var m=[];B(b.variants,function(a,b){m.push(new Q(b,parseFloat(a.probability),a.content))});if(b=ta(m,d&&d.chosenVariant))return new qa(a,e,g,b,c,j,f)}function ta(a,b){var c;w(b)&&(c=C(a,function(a){return a.e===b}));w(c)||(c=va(a));return c}
function va(a){var b=Math.random();return C(a,function(a){b-=a.J;return b<0})}function wa(a,b,c){var d=p.location.href,e=[encodeURIComponent(a),encodeURIComponent(d),b].join(",");B(c,function(a){e+=","+[a.test.e,a.test.i.e,encodeURIComponent(a.f)].join(",")});return e}function xa(a,b){if(a===b)return k;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return o;if(c.pop()!==d.pop())return o}return k}
function ya(){var a=p.document.head||p.document.getElementsByTagName("head")[0],b=p.document.createElement("style");b.id="chartbeat-flicker-control-style";b.type="text/css";b.styleSheet?b.styleSheet.cssText="body { visibility: hidden !important; }":b.appendChild(document.createTextNode("body { visibility: hidden !important; }"));a.appendChild(b)}function za(){return p.document.getElementById("chartbeat-flicker-control-style")||p.document.getElementById("chartbeat-body-hider")}
function Aa(){var a=za();a&&a.parentNode.removeChild(a)}function qa(a,b,c,d,e,f,g){this.e=a;this.k=b;this.f=g;this.D=c;this.i=d;this.q=e;this.j=o;this.G=f}function Q(a,b,c){this.e=a;this.J=b;this.content=c}function Ba(a){var b={};b.s=a.status;b.c=a.code;b.m=a.message;var c=n;if(a.data!==n)c={},c.s=a.data.L,c.g=a.data.q,c.m=a.data.I;b.d=c;return b}function Ca(a){if(p.document&&p.document.body)a();else var b=D(function(){p.document&&p.document.body&&(F(b),a())},50)};function Da(a,b){for(var c=b||document.documentElement,d=[],e=n,f=a,g,j,h,m,l,t;f&&f!==c;){g=f.nodeName.toLowerCase();e=f;j=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){h=f.children;m=0;for(l=0,t=h.length;l<t;l++){if(e===h[l]){g+="["+(1+l-m)+"]";break}h[l].nodeName!==j&&m++}}d.unshift(g)}return d.join("/")}
var R=function(){function a(a,b,c){b==="href"?(a=a.href||"",c=c||"",a=a.replace(d,""),c=c.replace(d,"")):a=a.getAttribute(b);return a===c}var b=/^\*\[@id='(.+?)'\](?:\[@([a-z-]+)='(.*)'\])?$/,c=/^([a-z][a-z0-9-]*)\[(\d+)\](?:\[@([a-z-]+)='(.*)'\])?$/,d=/^http(s)?\:\/\//;return function(d,f){var g=n;a:{for(var g=0,j=d.indexOf("/"),h=d.indexOf("'"),m=[];j!==-1;)if(h!==-1&&h<j){h=d.indexOf("'",h+1);if(h==-1){g=n;break a}j=d.indexOf("/",h+1);h=d.indexOf("'",h+1)}else m.push(d.substring(g,j)),g=j+1,j=
d.indexOf("/",g);g<d.length&&m.push(d.substring(g,d.length));g=m}if(!g||g.length==0)return f?f:n;var l,t,A,x,E,h=g.shift();if(f)j=f;else{if(h==="body")j=document.body;else{l=b.exec(h);if(!l)return n;j=document.getElementById(l[1]);if(!j)return n;t=l[2];l=l[3];if(t&&!a(j,t,l))return n}h=g.shift()}for(;w(h);){l=c.exec(h);if(!l)return n;h=l[1];m=parseInt(l[2],10);t=l[3];l=l[4];if(isNaN(m))return n;A=j.children;E=A.length;if(E===0)return n;for(x=0;x<E;x++){if(A[x].nodeName&&A[x].nodeName.toLowerCase()===
h&&(m--,m===0)){j=A[x];if(t&&!a(j,t,l))return n;break}if(x===E-1)return n}h=g.shift()}return j}}();function Ea(a){if(!("querySelectorAll"in document))return[];a=/^a\[@href='(.+?)'\]$/.exec(a);if(!a)return n;a=document.querySelectorAll('a[href="'+a[1]+'"]');a.length<1&&(a=n);return a?Array.prototype.slice.call(a):[]}function Fa(a){var b=n,b=L(a,function(a){return a.id}),c=Da(a,b);b&&(c&&(c="/"+c),c="*[@id='"+b.id+"']"+c);c+="[@href='"+a.href+"']";return c};function S(a){this.u=a;this.n=[];var b=this.u,a=b.topStorageDomain,b=b.domain,c=p.location.hostname;this.N=a?a:xa(c,b)?b:c.replace(/^www\./,"");this.C=new K("_t_");this.l=T;a=ja;M()[a]=k}
function Ga(a){if(!a.z){a.z=k;var b=a.B,c=a.v,d=a.C.b("tests"),e={};d.length>0&&(e=q(d));var f=sa(c,e);a.n=pa(b,f,e);var g=a.n,j={domain:"."+a.N,w:6E4,path:"/"};a.p=function(a){var b,a=a||window.event;if(b=!a?n:L(a.target||a.srcElement,ia,10))if(a=Ha(b,g),a.length){var c;if(b===n||typeof b==="undefined")c="unknown";else if(b.tagName==="A"&&b.href)c=b.href;c=wa(c,a[0].test.q,a);a=(a=I.b("_chartbeat6"))?a.split("::"):[];a.length>=10&&a.splice(0,a.length-10+1);a.push(c);c="_chartbeat6="+a.join("::");
a="";j&&j.constructor===Object&&(j.w&&(b=new Date,b.setTime(b.getTime()+j.w),a+="; expires="+b.toGMTString()),j.domain&&(a+="; domain="+j.domain),j.path&&(a+="; path="+j.path));document.cookie=c+a}};a=v(function(){var a=this.p,b=p.document.body;b.addEventListener?b.addEventListener("click",a,k):b.attachEvent&&b.attachEvent("onclick",a);Ia(this,g,f.e)},a);Ca(a)}}
function Ia(a,b,c){var d=z(),e=v(function(){var a=z()-d>=5E3,e=p.document.readyState==="complete",j;a||(j=Ja(b,c));if(a||j||e)F(this.t),Ka(this)},a);a.t=D(e,50);e()}
function Ka(a){Aa();var b={},c=[],d=o,e="m";B(a.n,function(a){if(a.e==="lift_exp")e=a.i.e;if(a.j){d=k;var f=[];B(a.anchors,function(a){f.push(a.f)});b[a.e]={chosenVariant:a.i.e,specificLocation:f}}else c.push(a.e)});if(d)b.lift_exp=e,a.C.create("tests",ca(b),3600),e==="m"&&delete b.lift_exp;var f={status:La,data:n,code:i,message:i};a.l!==T?(f.status=Ma,f.code=a.l):(a={L:b,q:e,I:c},f.status=Na,f.data=a);N(["t",Ba(f)])}function Oa(a){var b=a.u;N(["v",function(){a.terminate();Pa(a,b)}])}
S.prototype.K=function(a){if(Object.prototype.toString.call(a)==="[object Array]"&&y(a[0])&&a[0]==="readyForTesting")a[1]?Ga(this):this.A=o};function Qa(a){a.l=Ra;Ka(a)}S.prototype.terminate=function(){this.l=T;var a=this.p,b=p.document.body;b.removeEventListener?b.removeEventListener("click",a,k):b.detachEvent&&b.detachEvent("onclick",a);this.p=i;F(this.t);this.v=this.B=this.n=this.t=n;this.z=o};
function Pa(a,b){Oa(a);if(J.b("_cb_ip")==="1")Qa(a);else{var c=na(b);if(w(c))w(b.flickerControl)||(b.flickerControl=k),b.flickerControl&&(G(Aa,1E3),za()||ya()),oa(c,function(b,c){a.B=b;a.v=c;a.A=k;for(var f=v(a.K,a),g=p._cbm||[];g.length;)f(g.shift());p._cbm={push:f};a.A&&Ga(a)},function(){})}}
function Ja(a,b){var c=[];B(a,function(a,e){c.push(o);if(a.j)c[e]=k;else if(!a.f||a.f===a.k){var f=R(a.k);if(f)var g=R(a.D,f);if(f&&g){c[e]=k;if(b!=="c"&&"textContent"in document.body)g.textContent=a.i.content;a.anchors=[{element:f,f:a.k}];a.j=k}}else{a.anchors=[];var j=a.G;(f=Ea(a.k))&&f.length>0&&B(f,function(f){if(f)var g=R(a.D,f);g&&(g.textContent==j||(g=n));if(f&&g){c[e]=k;if(b!=="c"&&"textContent"in document.body)g.textContent=a.i.content;a.anchors.push({element:f,f:Fa(f)});a.j=k}})}});return c.indexOf(o)===
-1}
function Ha(a,b){var c=[],d=n,e=101,f=o;B(b,function(b){f||B(b.anchors,function(c){if(!f)if(c.element===a)d={test:b,f:c.f},f=k;else if(c.element.href===a.href){var h;var m=c.element.getBoundingClientRect(),l=a.getBoundingClientRect();m.right-m.left>0&&m.bottom-m.top>0&&l.right-l.left>0&&l.bottom-l.top>0?(h=Math.max(m.left,l.left)-Math.min(m.right,l.right),m=Math.max(m.top,l.top)-Math.min(m.bottom,l.bottom),h=h<=0?Math.max(m,0):m<=0?h:Math.sqrt(h*h+m*m)):h=i;h<e&&(d={test:b,f:c.f},e=h)}})});d&&c.push(d);
return c}var T=0,Ra=2,Na="s",Ma="e",La="f";var U=p._sf_async_config;U.domain=U.domain||p.location.hostname;U.domain=U.domain.replace(/^www\./,"");var V;a:{var W=n;if(U.useCanonical&&(W=ka())){V=W;break a}var X=p.location,W=O(X.pathname),Y=X.search||"",Y=Y.replace(/PHPSESSID=[^&]+/,""),Z=/&utm_[^=]+=[^&]+/ig,$=Z.exec(X.search);$&&(Y=Y.replace(Z,""));Z=/\?utm_[^=]+=[^&]+(.*)/i;($=Z.exec(Y))&&(Y=Y.replace(Z,$[1]!=""?"?"+$[1]:""));V=W+Y}U.path=U.path||V;var Sa=new S(U);Pa(Sa,U);})();
